#!/bin/bash

set -e
set -o pipefail

gecho 'Pulling master'
gecho ''

git pull

gecho ''
gecho 'Pushing to master'
gecho ''

git push

gecho ''
gecho 'Preparing wiki post, watch your browser...'
gecho ''

wiki 1
