#! /bin/bash
# push the last commit to master and b.

set -e
set -o pipefail

last_commit=`git lastcom`

gecho 'Pulling master'
gecho ''

git pull

gecho ''
gecho 'Pushing to master'
gecho ''

git push

last_branch=`git lastbr`

gecho ''
gecho "Switching to branch $last_branch"
gecho ''

git checkout $last_branch

gecho ''
gecho "Cherry-picking commit $last_commit"
gecho ''

git cherry-pick $last_commit

gecho ''
gecho "Pulling $last_branch"
gecho ''

git pull

gecho ''
gecho "Pushing $last_branch"
gecho ''

git push
git checkout master

gecho ''
gecho 'Preparing wiki post, watch your browser...'
gecho ''

wiki 2
